-- =========================================================================
-- VOSTOKPRIBOR Industrial Enterprise Suite - Online Shop B2B Database Setup
-- Compatible with MariaDB 10.4+ / MySQL 5.7+ / MySQL 8.0+
-- Fully Idempotent Setup Script: Safe to execute on new or existing databases
-- Generated: 2026-09-29 23:38:28
-- =========================================================================

SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

-- -------------------------------------------------------------------------
-- Table Structure: `customers`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers` (
  `cus_id` varchar(10) NOT NULL,
  `company_name` varchar(150) NOT NULL,
  `sector` varchar(100) DEFAULT NULL,
  `primary_contact_name` varchar(150) DEFAULT NULL,
  `primary_contact_email` varchar(150) DEFAULT NULL,
  `account_manager_emp_id` varchar(10) DEFAULT NULL,
  `onboarded_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `phone` varchar(50) DEFAULT NULL,
  `headquarters` varchar(255) DEFAULT NULL,
  `tax_id` varchar(50) DEFAULT NULL,
  `health_score` int(11) DEFAULT 95,
  `account_tier` varchar(50) DEFAULT 'Enterprise',
  `status` varchar(50) DEFAULT 'Active',
  PRIMARY KEY (`cus_id`),
  KEY `fk_customers_account_manager_emp_id` (`account_manager_emp_id`),
  CONSTRAINT `fk_customers_account_manager_emp_id` FOREIGN KEY (`account_manager_emp_id`) REFERENCES `employees` (`emp_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for `customers` (16 rows)
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1001', 'Severstal Metallurgy PJSC', 'Heavy Industry & Metallurgy', 'P. V. Cherepanov', 'procurement@severstal.com', 'EMP-1006', '2026-09-19 13:35:40', '+7 (8202) 53-88-00', 'Mira Street 30, Cherepovets, Vologda Region, 162600, Russian Federation', 'INN 3528000597', '94', 'Strategic Tier-1', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1002', 'Novolipetsk Steel (NLMK)', 'Ferrous Metallurgy', 'Alexei Voronov', 'automation@nlmk.com', 'EMP-1010', '2026-09-19 13:35:40', '+7 (4742) 44-4009', 'Lipetsk, Lipetsk Oblast', 'INN 4823006703', '91', 'Tier-1 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1003', 'Norilsk Nickel Mining', 'Non-Ferrous Mining', 'Dmitry Kiselev', 'telemetry@nornickel.ru', 'EMP-1007', '2026-09-19 13:35:40', '+7 (3919) 25-1100', 'Talnakh / Norilsk, Krasnoyarsk Krai', 'INN 8401005730', '95', 'Strategic Tier-1', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1004', 'EVRAZ Consolidated', 'Ferrous Metallurgy', 'Maxim Gusev', 'm.gusev@evraz.com', 'EMP-1008', '2026-09-19 13:35:40', '+7 (3435) 49-7000', 'Nizhny Tagil, Sverdlovsk Oblast', 'INN 7715047418', '88', 'Tier-2 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1005', 'PhosAgro Chemical', 'Chemical & Agro', 'Sergey Belyakov', 's.belyakov@phosagro.ru', 'EMP-1006', '2026-09-19 13:35:40', '+7 (8153) 15-5000', 'Apatity, Murmansk Oblast', 'INN 7725542282', '96', 'Tier-2 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1006', 'Gazprom Neft Omsk', 'Oil & Gas', 'Roman Danilov', 'danilov.ra@omsk.gazprom-neft.ru', 'EMP-1007', '2026-09-19 13:35:40', '+7 (3812) 69-0000', 'Omsk, Omsk Oblast', 'INN 5504036333', '90', 'Strategic Tier-1', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1007', 'Chelyabinsk Pipe Plant', 'Ferrous Metallurgy', 'Dr. Andrei Vasiliev', 'a.vasiliev@chelpipe.ru', 'EMP-1010', '2026-09-19 13:35:40', '+7 (351) 259-8801', 'Chelyabinsk, Chelyabinsk Oblast', 'INN 7451010323', '94', 'Tier-1 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1008', 'Magnitogorsk Iron & Steel Works', 'Ferrous Metallurgy', 'Valery Semenov', 'v.semenov@mmk.ru', 'EMP-1008', '2026-09-19 13:35:40', '+7 (3519) 24-0012', 'Magnitogorsk, Chelyabinsk Oblast', 'INN 7414003638', '91', 'Strategic Tier-1', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1009', 'Uralchem Mineral Fertilizers', 'Chemical & Agro', 'Irina Kondratieva', 'i.kondratieva@uralchem.com', 'EMP-1006', '2026-09-19 13:35:40', '+7 (342) 219-4400', 'Perm, Perm Krai', 'INN 7703647595', '89', 'Tier-2 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1010', 'Central Rail Diagnostics', 'Railway Infrastructure', 'Konstantin Titov', 'titov@rail-diagnostics.ru', 'EMP-1007', '2026-09-19 13:35:40', '+7 (499) 262-9901', 'Moscow, Central District', 'INN 7708503727', '85', 'Tier-2 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1011', 'API Test Industrial Corp', 'Aerospace Defense', 'Major Test Contact', 'contact@testcorp.ru', 'EMP-1006', '2026-09-29 19:55:23', '+7 (495) 999-0011', 'Moscow, RU', '', '95', 'Tier-1 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1012', 'Temporary Deletion Test Corp', 'Chemical Refining', '', '', 'EMP-1006', '2026-09-29 19:58:08', '', 'Moscow, RU', '', '95', 'Tier-1 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1013', 'API Test Industrial Corp', 'Aerospace Defense', 'Major Test Contact', 'contact@testcorp.ru', 'EMP-1006', '2026-09-29 19:59:57', '+7 (495) 999-0011', 'Moscow, RU', '', '95', 'Tier-1 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1014', 'Direct API Test Corp', 'Chemical Refining', 'Igor Chemist', 'igor@directtest.ru', 'EMP-1006', '2026-09-29 20:08:32', '', 'Moscow, RU', '', '95', 'Tier-1 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1015', 'Direct API Test Corp', 'Chemical Refining', 'Igor Chemist', 'igor@directtest.ru', 'EMP-1006', '2026-09-29 20:09:16', '', 'Moscow, RU', '', '95', 'Tier-1 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);
INSERT INTO `customers` (`cus_id`, `company_name`, `sector`, `primary_contact_name`, `primary_contact_email`, `account_manager_emp_id`, `onboarded_at`, `phone`, `headquarters`, `tax_id`, `health_score`, `account_tier`, `status`) VALUES ('CUS-1016', 'Dynamic Test Co', 'Industrial Automation', 'Dynamic Lead', 'dyn@test.ru', 'EMP-1006', '2026-09-29 20:09:27', NULL, NULL, NULL, '90', 'Tier-1 Enterprise', 'Active') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `company_name` = VALUES(`company_name`), `sector` = VALUES(`sector`), `primary_contact_name` = VALUES(`primary_contact_name`), `primary_contact_email` = VALUES(`primary_contact_email`), `account_manager_emp_id` = VALUES(`account_manager_emp_id`), `onboarded_at` = VALUES(`onboarded_at`), `phone` = VALUES(`phone`), `headquarters` = VALUES(`headquarters`), `tax_id` = VALUES(`tax_id`), `health_score` = VALUES(`health_score`), `account_tier` = VALUES(`account_tier`), `status` = VALUES(`status`);

-- -------------------------------------------------------------------------
-- Table Structure: `customer_accounts`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer_accounts` (
  `account_id` int(11) NOT NULL AUTO_INCREMENT,
  `cus_id` varchar(10) NOT NULL,
  `username` varchar(100) NOT NULL,
  `email` varchar(150) DEFAULT NULL,
  `password_hash` varchar(255) NOT NULL,
  `mfa_enabled` tinyint(1) DEFAULT 0,
  `status` varchar(20) DEFAULT 'Active',
  `last_login` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`account_id`),
  UNIQUE KEY `idx_cus_account_username` (`username`),
  KEY `idx_cus_id` (`cus_id`),
  CONSTRAINT `fk_customer_accounts_cus_id` FOREIGN KEY (`cus_id`) REFERENCES `customers` (`cus_id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for `customer_accounts` (17 rows)
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('1', 'CUS-1001', 'sergei.makarov', 's.makarov@aral-geomatics.kz', '$2y$10$eE0m1VvQ11a0u.J0PZ0XxeE/y/eG5zS8vM/oU29Vq4kY1Q1qG9r7m', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('2', 'CUS-1001', 'CLT-77210', 'client77210@vostokpribor.local', '$2y$10$eE0m1VvQ11a0u.J0PZ0XxeE/y/eG5zS8vM/oU29Vq4kY1Q1qG9r7m', '0', 'Active', '2026-09-30 02:38:10', '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('3', 'CUS-1001', 'CUS-1001', 'cus1001@aral-geomatics.kz', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('4', 'CUS-1002', 'kristaps.ozols', 'k.ozols@baltnord-systems.eu', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('5', 'CUS-1002', 'SHP-VP-11', 'b2b-buyer11@baltnord.eu', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('6', 'CUS-1002', 'CUS-1002', 'cus1002@baltnord.eu', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('7', 'CUS-1003', 'yerlan.bektemis', 'y.bektemis@steppemining.kz', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('8', 'CUS-1003', 'CUS-1003', 'cus1003@steppemining.kz', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('9', 'CUS-1004', 'lukas.brandt', 'l.brandt@rheinwerk-inst.de', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('10', 'CUS-1004', 'CUS-1004', 'cus1004@rheinwerk.de', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('11', 'CUS-1005', 'dilshod.karim', 'd.karim@tashkent-precision.uz', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('12', 'CUS-1005', 'CUS-1005', 'cus1005@tashkent-precision.uz', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('13', 'CUS-1006', 'mara.kalnina', 'm.kalnina@daugava-optical.lv', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('14', 'CUS-1007', 'murad.safarov', 'm.safarov@caspian-robotics.az', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('15', 'CUS-1008', 'oleg.petrenko', 'o.petrenko@eurasia-water.ua', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('16', 'CUS-1009', 'ainur.sadyk', 'a.sadyk@altai-env.kz', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);
INSERT INTO `customer_accounts` (`account_id`, `cus_id`, `username`, `email`, `password_hash`, `mfa_enabled`, `status`, `last_login`, `created_at`) VALUES ('17', 'CUS-1010', 'tomas.varga', 't.varga@central-rail.hu', '$2y$12$sjpWNnksb35C7D8re5tdt.qqOiKDZqw7J2lmGOVPoyRBT5bDpEzGq', '0', 'Active', NULL, '2026-09-21 19:39:04') ON DUPLICATE KEY UPDATE `account_id` = VALUES(`account_id`), `cus_id` = VALUES(`cus_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password_hash` = VALUES(`password_hash`), `mfa_enabled` = VALUES(`mfa_enabled`), `status` = VALUES(`status`), `last_login` = VALUES(`last_login`), `created_at` = VALUES(`created_at`);

-- -------------------------------------------------------------------------
-- Table Structure: `products`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `products` (
  `prod_id` varchar(10) NOT NULL,
  `product_name` varchar(150) NOT NULL,
  `billing_model` enum('PerUnit','PerProject','SubscriptionMonthly','SubscriptionAnnual','AnnualContract') NOT NULL,
  `description` text DEFAULT NULL,
  PRIMARY KEY (`prod_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for `products` (10 rows)
INSERT INTO `products` (`prod_id`, `product_name`, `billing_model`, `description`) VALUES ('PROD-1001', 'Industrial Optical Sensor Package', 'PerUnit', NULL) ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `product_name` = VALUES(`product_name`), `billing_model` = VALUES(`billing_model`), `description` = VALUES(`description`);
INSERT INTO `products` (`prod_id`, `product_name`, `billing_model`, `description`) VALUES ('PROD-1002', 'Precision Geodetic Measurement Kit', 'PerUnit', NULL) ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `product_name` = VALUES(`product_name`), `billing_model` = VALUES(`billing_model`), `description` = VALUES(`description`);
INSERT INTO `products` (`prod_id`, `product_name`, `billing_model`, `description`) VALUES ('PROD-1003', 'Automated Calibration Station', 'PerProject', NULL) ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `product_name` = VALUES(`product_name`), `billing_model` = VALUES(`billing_model`), `description` = VALUES(`description`);
INSERT INTO `products` (`prod_id`, `product_name`, `billing_model`, `description`) VALUES ('PROD-1004', 'Industrial PLC Integration', 'PerProject', NULL) ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `product_name` = VALUES(`product_name`), `billing_model` = VALUES(`billing_model`), `description` = VALUES(`description`);
INSERT INTO `products` (`prod_id`, `product_name`, `billing_model`, `description`) VALUES ('PROD-1005', 'Remote Monitoring Gateway', 'PerUnit', NULL) ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `product_name` = VALUES(`product_name`), `billing_model` = VALUES(`billing_model`), `description` = VALUES(`description`);
INSERT INTO `products` (`prod_id`, `product_name`, `billing_model`, `description`) VALUES ('PROD-1006', 'Optical Inspection System', 'PerProject', NULL) ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `product_name` = VALUES(`product_name`), `billing_model` = VALUES(`billing_model`), `description` = VALUES(`description`);
INSERT INTO `products` (`prod_id`, `product_name`, `billing_model`, `description`) VALUES ('PROD-1007', 'Industrial Lifecycle Support', 'SubscriptionAnnual', NULL) ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `product_name` = VALUES(`product_name`), `billing_model` = VALUES(`billing_model`), `description` = VALUES(`description`);
INSERT INTO `products` (`prod_id`, `product_name`, `billing_model`, `description`) VALUES ('PROD-1008', 'Automation Software Integration', 'PerProject', NULL) ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `product_name` = VALUES(`product_name`), `billing_model` = VALUES(`billing_model`), `description` = VALUES(`description`);
INSERT INTO `products` (`prod_id`, `product_name`, `billing_model`, `description`) VALUES ('PROD-1009', 'Enterprise Logistics Management', 'SubscriptionMonthly', NULL) ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `product_name` = VALUES(`product_name`), `billing_model` = VALUES(`billing_model`), `description` = VALUES(`description`);
INSERT INTO `products` (`prod_id`, `product_name`, `billing_model`, `description`) VALUES ('PROD-1010', 'Preventive Instrument Maintenance', 'AnnualContract', NULL) ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `product_name` = VALUES(`product_name`), `billing_model` = VALUES(`billing_model`), `description` = VALUES(`description`);

-- -------------------------------------------------------------------------
-- Table Structure: `product_inventory`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_inventory` (
  `prod_id` varchar(10) NOT NULL,
  `warehouse_location` varchar(100) DEFAULT NULL,
  `quantity_on_hand` int(11) DEFAULT 0,
  `reorder_level` int(11) DEFAULT 0,
  PRIMARY KEY (`prod_id`),
  CONSTRAINT `fk_product_inventory_prod_id` FOREIGN KEY (`prod_id`) REFERENCES `products` (`prod_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for `product_inventory` (10 rows)
INSERT INTO `product_inventory` (`prod_id`, `warehouse_location`, `quantity_on_hand`, `reorder_level`) VALUES ('PROD-1001', 'WH-North-A1', '45', '15') ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `warehouse_location` = VALUES(`warehouse_location`), `quantity_on_hand` = VALUES(`quantity_on_hand`), `reorder_level` = VALUES(`reorder_level`);
INSERT INTO `product_inventory` (`prod_id`, `warehouse_location`, `quantity_on_hand`, `reorder_level`) VALUES ('PROD-1002', 'WH-Central-B3', '57', '15') ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `warehouse_location` = VALUES(`warehouse_location`), `quantity_on_hand` = VALUES(`quantity_on_hand`), `reorder_level` = VALUES(`reorder_level`);
INSERT INTO `product_inventory` (`prod_id`, `warehouse_location`, `quantity_on_hand`, `reorder_level`) VALUES ('PROD-1003', 'WH-East-C2', '69', '15') ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `warehouse_location` = VALUES(`warehouse_location`), `quantity_on_hand` = VALUES(`quantity_on_hand`), `reorder_level` = VALUES(`reorder_level`);
INSERT INTO `product_inventory` (`prod_id`, `warehouse_location`, `quantity_on_hand`, `reorder_level`) VALUES ('PROD-1004', 'WH-South-D4', '81', '15') ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `warehouse_location` = VALUES(`warehouse_location`), `quantity_on_hand` = VALUES(`quantity_on_hand`), `reorder_level` = VALUES(`reorder_level`);
INSERT INTO `product_inventory` (`prod_id`, `warehouse_location`, `quantity_on_hand`, `reorder_level`) VALUES ('PROD-1005', 'WH-North-A1', '93', '15') ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `warehouse_location` = VALUES(`warehouse_location`), `quantity_on_hand` = VALUES(`quantity_on_hand`), `reorder_level` = VALUES(`reorder_level`);
INSERT INTO `product_inventory` (`prod_id`, `warehouse_location`, `quantity_on_hand`, `reorder_level`) VALUES ('PROD-1006', 'WH-Central-B3', '105', '15') ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `warehouse_location` = VALUES(`warehouse_location`), `quantity_on_hand` = VALUES(`quantity_on_hand`), `reorder_level` = VALUES(`reorder_level`);
INSERT INTO `product_inventory` (`prod_id`, `warehouse_location`, `quantity_on_hand`, `reorder_level`) VALUES ('PROD-1007', 'WH-East-C2', '117', '15') ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `warehouse_location` = VALUES(`warehouse_location`), `quantity_on_hand` = VALUES(`quantity_on_hand`), `reorder_level` = VALUES(`reorder_level`);
INSERT INTO `product_inventory` (`prod_id`, `warehouse_location`, `quantity_on_hand`, `reorder_level`) VALUES ('PROD-1008', 'WH-South-D4', '129', '15') ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `warehouse_location` = VALUES(`warehouse_location`), `quantity_on_hand` = VALUES(`quantity_on_hand`), `reorder_level` = VALUES(`reorder_level`);
INSERT INTO `product_inventory` (`prod_id`, `warehouse_location`, `quantity_on_hand`, `reorder_level`) VALUES ('PROD-1009', 'WH-North-A1', '141', '15') ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `warehouse_location` = VALUES(`warehouse_location`), `quantity_on_hand` = VALUES(`quantity_on_hand`), `reorder_level` = VALUES(`reorder_level`);
INSERT INTO `product_inventory` (`prod_id`, `warehouse_location`, `quantity_on_hand`, `reorder_level`) VALUES ('PROD-1010', 'WH-Central-B3', '153', '15') ON DUPLICATE KEY UPDATE `prod_id` = VALUES(`prod_id`), `warehouse_location` = VALUES(`warehouse_location`), `quantity_on_hand` = VALUES(`quantity_on_hand`), `reorder_level` = VALUES(`reorder_level`);

-- -------------------------------------------------------------------------
-- Table Structure: `customer_pricing`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer_pricing` (
  `cus_id` varchar(10) NOT NULL,
  `prod_id` varchar(10) NOT NULL,
  `special_price` decimal(12,2) DEFAULT NULL,
  PRIMARY KEY (`cus_id`,`prod_id`),
  KEY `fk_customer_pricing_prod_id` (`prod_id`),
  CONSTRAINT `fk_customer_pricing_cus_id` FOREIGN KEY (`cus_id`) REFERENCES `customers` (`cus_id`),
  CONSTRAINT `fk_customer_pricing_prod_id` FOREIGN KEY (`prod_id`) REFERENCES `products` (`prod_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for `customer_pricing` (6 rows)
INSERT INTO `customer_pricing` (`cus_id`, `prod_id`, `special_price`) VALUES ('CUS-1001', 'PROD-1001', '2250.00') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `special_price` = VALUES(`special_price`);
INSERT INTO `customer_pricing` (`cus_id`, `prod_id`, `special_price`) VALUES ('CUS-1001', 'PROD-1002', '3100.00') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `special_price` = VALUES(`special_price`);
INSERT INTO `customer_pricing` (`cus_id`, `prod_id`, `special_price`) VALUES ('CUS-1002', 'PROD-1003', '1850.00') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `special_price` = VALUES(`special_price`);
INSERT INTO `customer_pricing` (`cus_id`, `prod_id`, `special_price`) VALUES ('CUS-1003', 'PROD-1004', '4200.00') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `special_price` = VALUES(`special_price`);
INSERT INTO `customer_pricing` (`cus_id`, `prod_id`, `special_price`) VALUES ('CUS-1004', 'PROD-1005', '850.00') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `special_price` = VALUES(`special_price`);
INSERT INTO `customer_pricing` (`cus_id`, `prod_id`, `special_price`) VALUES ('CUS-1005', 'PROD-1001', '2100.00') ON DUPLICATE KEY UPDATE `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `special_price` = VALUES(`special_price`);

-- -------------------------------------------------------------------------
-- Table Structure: `projects`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `projects` (
  `prj_id` varchar(15) NOT NULL,
  `project_name` varchar(150) DEFAULT NULL,
  `cus_id` varchar(10) NOT NULL,
  `project_manager_emp_id` varchar(10) DEFAULT NULL,
  `budget` decimal(14,2) DEFAULT NULL,
  `currency` char(3) DEFAULT 'EUR',
  `status` enum('Planning','Procurement','Design','Integration','Testing','Execution','ContractReview','Maintenance','Closed') DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `progress_percent` int(11) DEFAULT 0,
  `facility_location` varchar(255) DEFAULT NULL,
  `scope_summary` text DEFAULT NULL,
  PRIMARY KEY (`prj_id`),
  KEY `fk_projects_cus_id` (`cus_id`),
  KEY `fk_projects_project_manager_emp_id` (`project_manager_emp_id`),
  CONSTRAINT `fk_projects_cus_id` FOREIGN KEY (`cus_id`) REFERENCES `customers` (`cus_id`),
  CONSTRAINT `fk_projects_project_manager_emp_id` FOREIGN KEY (`project_manager_emp_id`) REFERENCES `employees` (`emp_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for `projects` (8 rows)
INSERT INTO `projects` (`prj_id`, `project_name`, `cus_id`, `project_manager_emp_id`, `budget`, `currency`, `status`, `start_date`, `end_date`, `progress_percent`, `facility_location`, `scope_summary`) VALUES ('PRJ-VP-4411', 'Rail Mill Laser Profiler & Flaw Detection Array', 'CUS-1004', 'EMP-1008', '1650000.00', 'USD', 'Procurement', '2024-04-01', '2027-01-15', '35', 'Rail & Structural Mill · Nizhny Tagil', 'High-speed eddy-current flaw detector array for continuous railway rail profiles.') ON DUPLICATE KEY UPDATE `prj_id` = VALUES(`prj_id`), `project_name` = VALUES(`project_name`), `cus_id` = VALUES(`cus_id`), `project_manager_emp_id` = VALUES(`project_manager_emp_id`), `budget` = VALUES(`budget`), `currency` = VALUES(`currency`), `status` = VALUES(`status`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `progress_percent` = VALUES(`progress_percent`), `facility_location` = VALUES(`facility_location`), `scope_summary` = VALUES(`scope_summary`);
INSERT INTO `projects` (`prj_id`, `project_name`, `cus_id`, `project_manager_emp_id`, `budget`, `currency`, `status`, `start_date`, `end_date`, `progress_percent`, `facility_location`, `scope_summary`) VALUES ('PRJ-VP-5510', 'Continuous Casting Machine #3 Flow Control', 'CUS-1001', 'EMP-1018', '890000.00', 'USD', '', '2023-09-01', '2024-04-30', '100', 'Cherepovets Works - CCM3', 'Hydraulic actuator servo-valves overhaul and dual-redundant flow sensors.') ON DUPLICATE KEY UPDATE `prj_id` = VALUES(`prj_id`), `project_name` = VALUES(`project_name`), `cus_id` = VALUES(`cus_id`), `project_manager_emp_id` = VALUES(`project_manager_emp_id`), `budget` = VALUES(`budget`), `currency` = VALUES(`currency`), `status` = VALUES(`status`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `progress_percent` = VALUES(`progress_percent`), `facility_location` = VALUES(`facility_location`), `scope_summary` = VALUES(`scope_summary`);
INSERT INTO `projects` (`prj_id`, `project_name`, `cus_id`, `project_manager_emp_id`, `budget`, `currency`, `status`, `start_date`, `end_date`, `progress_percent`, `facility_location`, `scope_summary`) VALUES ('PRJ-VP-5520', 'Coke Oven Battery Temperature Profiling & IR Cameras', 'CUS-1002', 'EMP-1010', '920000.00', 'USD', 'Integration', '2024-02-15', '2026-11-20', '60', 'Coke Plant Shop #3 · Lipetsk', 'Continuous thermal imaging array with automatic hot-spot flame detection alerting.') ON DUPLICATE KEY UPDATE `prj_id` = VALUES(`prj_id`), `project_name` = VALUES(`project_name`), `cus_id` = VALUES(`cus_id`), `project_manager_emp_id` = VALUES(`project_manager_emp_id`), `budget` = VALUES(`budget`), `currency` = VALUES(`currency`), `status` = VALUES(`status`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `progress_percent` = VALUES(`progress_percent`), `facility_location` = VALUES(`facility_location`), `scope_summary` = VALUES(`scope_summary`);
INSERT INTO `projects` (`prj_id`, `project_name`, `cus_id`, `project_manager_emp_id`, `budget`, `currency`, `status`, `start_date`, `end_date`, `progress_percent`, `facility_location`, `scope_summary`) VALUES ('PRJ-VP-6610', 'Talnakh Concentrator Flotation Telemetry Grid', 'CUS-1003', 'EMP-1007', '2400000.00', 'USD', 'Execution', '2024-02-10', '2026-12-18', '80', 'Talnakh Concentrator Division · Norilsk', 'Sub-zero froth height acoustic telemetry and slurry density radiometric densitometer network.') ON DUPLICATE KEY UPDATE `prj_id` = VALUES(`prj_id`), `project_name` = VALUES(`project_name`), `cus_id` = VALUES(`cus_id`), `project_manager_emp_id` = VALUES(`project_manager_emp_id`), `budget` = VALUES(`budget`), `currency` = VALUES(`currency`), `status` = VALUES(`status`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `progress_percent` = VALUES(`progress_percent`), `facility_location` = VALUES(`facility_location`), `scope_summary` = VALUES(`scope_summary`);
INSERT INTO `projects` (`prj_id`, `project_name`, `cus_id`, `project_manager_emp_id`, `budget`, `currency`, `status`, `start_date`, `end_date`, `progress_percent`, `facility_location`, `scope_summary`) VALUES ('PRJ-VP-6840', 'Oxygen Converter Shop #2 Telemetry', 'CUS-1001', 'EMP-1004', '1240000.00', 'USD', '', '2024-08-15', '2025-03-31', '40', 'Cherepovets Works - BOF2', 'High-temp optical pyrometry loop integration and SIL-3 safety interlock calibration.') ON DUPLICATE KEY UPDATE `prj_id` = VALUES(`prj_id`), `project_name` = VALUES(`project_name`), `cus_id` = VALUES(`cus_id`), `project_manager_emp_id` = VALUES(`project_manager_emp_id`), `budget` = VALUES(`budget`), `currency` = VALUES(`currency`), `status` = VALUES(`status`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `progress_percent` = VALUES(`progress_percent`), `facility_location` = VALUES(`facility_location`), `scope_summary` = VALUES(`scope_summary`);
INSERT INTO `projects` (`prj_id`, `project_name`, `cus_id`, `project_manager_emp_id`, `budget`, `currency`, `status`, `start_date`, `end_date`, `progress_percent`, `facility_location`, `scope_summary`) VALUES ('PRJ-VP-7721', 'Blast Furnace #5 SCADA Modernization', 'CUS-1001', 'EMP-1006', '1850000.00', 'USD', 'Execution', '2024-01-15', '2026-11-28', '65', 'Cherepovets Ironmaking Plant #4', 'Blast furnace off-gas telemetry, CO/CO2 infrared optical analyzers, and high-temp probe arrays.') ON DUPLICATE KEY UPDATE `prj_id` = VALUES(`prj_id`), `project_name` = VALUES(`project_name`), `cus_id` = VALUES(`cus_id`), `project_manager_emp_id` = VALUES(`project_manager_emp_id`), `budget` = VALUES(`budget`), `currency` = VALUES(`currency`), `status` = VALUES(`status`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `progress_percent` = VALUES(`progress_percent`), `facility_location` = VALUES(`facility_location`), `scope_summary` = VALUES(`scope_summary`);
INSERT INTO `projects` (`prj_id`, `project_name`, `cus_id`, `project_manager_emp_id`, `budget`, `currency`, `status`, `start_date`, `end_date`, `progress_percent`, `facility_location`, `scope_summary`) VALUES ('PRJ-VP-7804', 'Hot Strip Mill #2 Hydraulic Pressure Sensor Telemetry Retrofit', 'CUS-1001', 'EMP-1010', '640000.00', 'USD', 'Integration', '2024-03-01', '2026-12-20', '45', 'Rolling Mill Bay 2 · Cherepovets', 'Retrofit 48 high-pressure hydraulic transducers with real-time SCADA Modbus TCP gateway.') ON DUPLICATE KEY UPDATE `prj_id` = VALUES(`prj_id`), `project_name` = VALUES(`project_name`), `cus_id` = VALUES(`cus_id`), `project_manager_emp_id` = VALUES(`project_manager_emp_id`), `budget` = VALUES(`budget`), `currency` = VALUES(`currency`), `status` = VALUES(`status`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `progress_percent` = VALUES(`progress_percent`), `facility_location` = VALUES(`facility_location`), `scope_summary` = VALUES(`scope_summary`);
INSERT INTO `projects` (`prj_id`, `project_name`, `cus_id`, `project_manager_emp_id`, `budget`, `currency`, `status`, `start_date`, `end_date`, `progress_percent`, `facility_location`, `scope_summary`) VALUES ('PRJ-VP-8902', 'Continuous Casting Machine #3 Optical Thickness Gauges', 'CUS-1001', 'EMP-1006', '410000.00', 'USD', 'Design', '2024-05-01', '2027-02-15', '18', 'Steelmaking Shop #1 · Cherepovets', 'Triangulation laser profilometer pair for slab hot-geometry dimensional verification.') ON DUPLICATE KEY UPDATE `prj_id` = VALUES(`prj_id`), `project_name` = VALUES(`project_name`), `cus_id` = VALUES(`cus_id`), `project_manager_emp_id` = VALUES(`project_manager_emp_id`), `budget` = VALUES(`budget`), `currency` = VALUES(`currency`), `status` = VALUES(`status`), `start_date` = VALUES(`start_date`), `end_date` = VALUES(`end_date`), `progress_percent` = VALUES(`progress_percent`), `facility_location` = VALUES(`facility_location`), `scope_summary` = VALUES(`scope_summary`);

-- -------------------------------------------------------------------------
-- Table Structure: `orders`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders` (
  `order_id` int(11) NOT NULL AUTO_INCREMENT,
  `cus_id` varchar(10) NOT NULL,
  `order_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `status` varchar(30) DEFAULT 'Cart',
  `total_amount` decimal(14,2) DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  KEY `fk_orders_cus_id` (`cus_id`),
  CONSTRAINT `fk_orders_cus_id` FOREIGN KEY (`cus_id`) REFERENCES `customers` (`cus_id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for `orders` (6 rows)
INSERT INTO `orders` (`order_id`, `cus_id`, `order_date`, `status`, `total_amount`) VALUES ('1', 'CUS-1001', '2026-09-15 08:30:00', 'Shipped', '48500.00') ON DUPLICATE KEY UPDATE `order_id` = VALUES(`order_id`), `cus_id` = VALUES(`cus_id`), `order_date` = VALUES(`order_date`), `status` = VALUES(`status`), `total_amount` = VALUES(`total_amount`);
INSERT INTO `orders` (`order_id`, `cus_id`, `order_date`, `status`, `total_amount`) VALUES ('2', 'CUS-1003', '2026-09-18 11:20:00', 'Delivered', '128400.00') ON DUPLICATE KEY UPDATE `order_id` = VALUES(`order_id`), `cus_id` = VALUES(`cus_id`), `order_date` = VALUES(`order_date`), `status` = VALUES(`status`), `total_amount` = VALUES(`total_amount`);
INSERT INTO `orders` (`order_id`, `cus_id`, `order_date`, `status`, `total_amount`) VALUES ('3', 'CUS-1005', '2026-09-20 14:10:00', 'Processing', '31500.00') ON DUPLICATE KEY UPDATE `order_id` = VALUES(`order_id`), `cus_id` = VALUES(`cus_id`), `order_date` = VALUES(`order_date`), `status` = VALUES(`status`), `total_amount` = VALUES(`total_amount`);
INSERT INTO `orders` (`order_id`, `cus_id`, `order_date`, `status`, `total_amount`) VALUES ('4', 'CUS-1006', '2026-09-10 16:45:00', 'Delivered', '85000.00') ON DUPLICATE KEY UPDATE `order_id` = VALUES(`order_id`), `cus_id` = VALUES(`cus_id`), `order_date` = VALUES(`order_date`), `status` = VALUES(`status`), `total_amount` = VALUES(`total_amount`);
INSERT INTO `orders` (`order_id`, `cus_id`, `order_date`, `status`, `total_amount`) VALUES ('5', 'CUS-1010', '2026-09-21 09:00:00', 'Processing', '192000.00') ON DUPLICATE KEY UPDATE `order_id` = VALUES(`order_id`), `cus_id` = VALUES(`cus_id`), `order_date` = VALUES(`order_date`), `status` = VALUES(`status`), `total_amount` = VALUES(`total_amount`);
INSERT INTO `orders` (`order_id`, `cus_id`, `order_date`, `status`, `total_amount`) VALUES ('8', 'CUS-1001', '2026-09-30 02:14:46', 'Processing', '45000.00') ON DUPLICATE KEY UPDATE `order_id` = VALUES(`order_id`), `cus_id` = VALUES(`cus_id`), `order_date` = VALUES(`order_date`), `status` = VALUES(`status`), `total_amount` = VALUES(`total_amount`);

-- -------------------------------------------------------------------------
-- Table Structure: `order_items`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_items` (
  `order_item_id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) NOT NULL,
  `prod_id` varchar(10) NOT NULL,
  `quantity` int(11) NOT NULL,
  `unit_price` decimal(12,2) DEFAULT NULL,
  PRIMARY KEY (`order_item_id`),
  KEY `fk_order_items_order_id` (`order_id`),
  KEY `fk_order_items_prod_id` (`prod_id`),
  CONSTRAINT `fk_order_items_order_id` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`),
  CONSTRAINT `fk_order_items_prod_id` FOREIGN KEY (`prod_id`) REFERENCES `products` (`prod_id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for `order_items` (6 rows)
INSERT INTO `order_items` (`order_item_id`, `order_id`, `prod_id`, `quantity`, `unit_price`) VALUES ('1', '1', 'PROD-1001', '5', '12500.00') ON DUPLICATE KEY UPDATE `order_item_id` = VALUES(`order_item_id`), `order_id` = VALUES(`order_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`);
INSERT INTO `order_items` (`order_item_id`, `order_id`, `prod_id`, `quantity`, `unit_price`) VALUES ('2', '1', 'PROD-1002', '10', '8250.00') ON DUPLICATE KEY UPDATE `order_item_id` = VALUES(`order_item_id`), `order_id` = VALUES(`order_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`);
INSERT INTO `order_items` (`order_item_id`, `order_id`, `prod_id`, `quantity`, `unit_price`) VALUES ('3', '2', 'PROD-1003', '8', '18500.00') ON DUPLICATE KEY UPDATE `order_item_id` = VALUES(`order_item_id`), `order_id` = VALUES(`order_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`);
INSERT INTO `order_items` (`order_item_id`, `order_id`, `prod_id`, `quantity`, `unit_price`) VALUES ('4', '2', 'PROD-1004', '15', '10000.00') ON DUPLICATE KEY UPDATE `order_item_id` = VALUES(`order_item_id`), `order_id` = VALUES(`order_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`);
INSERT INTO `order_items` (`order_item_id`, `order_id`, `prod_id`, `quantity`, `unit_price`) VALUES ('5', '3', 'PROD-1005', '20', '22500.00') ON DUPLICATE KEY UPDATE `order_item_id` = VALUES(`order_item_id`), `order_id` = VALUES(`order_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`);
INSERT INTO `order_items` (`order_item_id`, `order_id`, `prod_id`, `quantity`, `unit_price`) VALUES ('8', '8', 'PROD-1001', '1', '45000.00') ON DUPLICATE KEY UPDATE `order_item_id` = VALUES(`order_item_id`), `order_id` = VALUES(`order_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`);

-- -------------------------------------------------------------------------
-- Table Structure: `quotes`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `quotes` (
  `quote_id` int(11) NOT NULL AUTO_INCREMENT,
  `cus_id` varchar(10) NOT NULL,
  `prod_id` varchar(10) NOT NULL,
  `quantity` int(11) NOT NULL,
  `unit_price` decimal(12,2) DEFAULT NULL,
  `created_by_emp_id` varchar(10) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `quote_ref` varchar(50) DEFAULT NULL,
  `equipment_scope` varchar(255) DEFAULT NULL,
  `valid_until` date DEFAULT NULL,
  `total_amount` decimal(14,2) DEFAULT NULL,
  `status` varchar(50) DEFAULT 'Pending Review',
  PRIMARY KEY (`quote_id`),
  KEY `fk_quotes_cus_id` (`cus_id`),
  KEY `fk_quotes_prod_id` (`prod_id`),
  KEY `fk_quotes_created_by_emp_id` (`created_by_emp_id`),
  CONSTRAINT `fk_quotes_created_by_emp_id` FOREIGN KEY (`created_by_emp_id`) REFERENCES `employees` (`emp_id`),
  CONSTRAINT `fk_quotes_cus_id` FOREIGN KEY (`cus_id`) REFERENCES `customers` (`cus_id`),
  CONSTRAINT `fk_quotes_prod_id` FOREIGN KEY (`prod_id`) REFERENCES `products` (`prod_id`)
) ENGINE=InnoDB AUTO_INCREMENT=100002 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for `quotes` (8 rows)
INSERT INTO `quotes` (`quote_id`, `cus_id`, `prod_id`, `quantity`, `unit_price`, `created_by_emp_id`, `created_at`, `quote_ref`, `equipment_scope`, `valid_until`, `total_amount`, `status`) VALUES ('1', 'CUS-1002', 'PROD-1001', '16', '26137.50', 'EMP-1010', '2026-09-29 22:25:06', 'QUO-9912', '16x High-Pressure Flowmeters HPF-900X with Industrial Hart Protocol', '2026-11-30', '418200.00', 'Delivered') ON DUPLICATE KEY UPDATE `quote_id` = VALUES(`quote_id`), `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`), `created_by_emp_id` = VALUES(`created_by_emp_id`), `created_at` = VALUES(`created_at`), `quote_ref` = VALUES(`quote_ref`), `equipment_scope` = VALUES(`equipment_scope`), `valid_until` = VALUES(`valid_until`), `total_amount` = VALUES(`total_amount`), `status` = VALUES(`status`);
INSERT INTO `quotes` (`quote_id`, `cus_id`, `prod_id`, `quantity`, `unit_price`, `created_by_emp_id`, `created_at`, `quote_ref`, `equipment_scope`, `valid_until`, `total_amount`, `status`) VALUES ('2', 'CUS-1001', 'PROD-1002', '2', '340000.00', 'EMP-1006', '2026-09-29 22:25:06', 'QUO-9918', 'Blast Furnace #5 Optical Spectrometry Skid & Calibration Module', '2026-12-15', '680000.00', 'Approved') ON DUPLICATE KEY UPDATE `quote_id` = VALUES(`quote_id`), `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`), `created_by_emp_id` = VALUES(`created_by_emp_id`), `created_at` = VALUES(`created_at`), `quote_ref` = VALUES(`quote_ref`), `equipment_scope` = VALUES(`equipment_scope`), `valid_until` = VALUES(`valid_until`), `total_amount` = VALUES(`total_amount`), `status` = VALUES(`status`);
INSERT INTO `quotes` (`quote_id`, `cus_id`, `prod_id`, `quantity`, `unit_price`, `created_by_emp_id`, `created_at`, `quote_ref`, `equipment_scope`, `valid_until`, `total_amount`, `status`) VALUES ('3', 'CUS-1003', 'PROD-1003', '40', '31000.00', 'EMP-1007', '2026-09-29 22:25:06', 'QUO-9924', 'Talnakh Flotation Telemetry Grid Transducers & Sub-Zero Junction Skids', '2026-12-31', '1240000.00', 'Under Review') ON DUPLICATE KEY UPDATE `quote_id` = VALUES(`quote_id`), `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`), `created_by_emp_id` = VALUES(`created_by_emp_id`), `created_at` = VALUES(`created_at`), `quote_ref` = VALUES(`quote_ref`), `equipment_scope` = VALUES(`equipment_scope`), `valid_until` = VALUES(`valid_until`), `total_amount` = VALUES(`total_amount`), `status` = VALUES(`status`);
INSERT INTO `quotes` (`quote_id`, `cus_id`, `prod_id`, `quantity`, `unit_price`, `created_by_emp_id`, `created_at`, `quote_ref`, `equipment_scope`, `valid_until`, `total_amount`, `status`) VALUES ('4', 'CUS-1007', 'PROD-1001', '1', '1450000.00', 'EMP-1010', '2026-09-29 22:25:06', 'QUO-9931', 'Seamless Casing Ultrasonic Flaw Detection Station with Automated Feeder', '2026-11-25', '1450000.00', 'Pending Review') ON DUPLICATE KEY UPDATE `quote_id` = VALUES(`quote_id`), `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`), `created_by_emp_id` = VALUES(`created_by_emp_id`), `created_at` = VALUES(`created_at`), `quote_ref` = VALUES(`quote_ref`), `equipment_scope` = VALUES(`equipment_scope`), `valid_until` = VALUES(`valid_until`), `total_amount` = VALUES(`total_amount`), `status` = VALUES(`status`);
INSERT INTO `quotes` (`quote_id`, `cus_id`, `prod_id`, `quantity`, `unit_price`, `created_by_emp_id`, `created_at`, `quote_ref`, `equipment_scope`, `valid_until`, `total_amount`, `status`) VALUES ('5', 'CUS-1001', 'PROD-1001', '1', '420000.00', 'EMP-1006', '2026-09-29 19:55:23', 'QUO-9088', 'Sensor Automation Modules', '2026-10-29', '420000.00', 'Delivered') ON DUPLICATE KEY UPDATE `quote_id` = VALUES(`quote_id`), `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`), `created_by_emp_id` = VALUES(`created_by_emp_id`), `created_at` = VALUES(`created_at`), `quote_ref` = VALUES(`quote_ref`), `equipment_scope` = VALUES(`equipment_scope`), `valid_until` = VALUES(`valid_until`), `total_amount` = VALUES(`total_amount`), `status` = VALUES(`status`);
INSERT INTO `quotes` (`quote_id`, `cus_id`, `prod_id`, `quantity`, `unit_price`, `created_by_emp_id`, `created_at`, `quote_ref`, `equipment_scope`, `valid_until`, `total_amount`, `status`) VALUES ('6', 'CUS-1001', 'PROD-1001', '1', '420000.00', 'EMP-1006', '2026-09-29 19:59:58', 'QUO-9800', 'Sensor Automation Modules', '2026-10-29', '420000.00', 'Delivered') ON DUPLICATE KEY UPDATE `quote_id` = VALUES(`quote_id`), `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`), `created_by_emp_id` = VALUES(`created_by_emp_id`), `created_at` = VALUES(`created_at`), `quote_ref` = VALUES(`quote_ref`), `equipment_scope` = VALUES(`equipment_scope`), `valid_until` = VALUES(`valid_until`), `total_amount` = VALUES(`total_amount`), `status` = VALUES(`status`);
INSERT INTO `quotes` (`quote_id`, `cus_id`, `prod_id`, `quantity`, `unit_price`, `created_by_emp_id`, `created_at`, `quote_ref`, `equipment_scope`, `valid_until`, `total_amount`, `status`) VALUES ('7', 'CUS-1001', 'PROD-1001', '1', '350000.00', 'EMP-1006', '2026-09-29 20:08:33', 'QUO-9005', 'Telemetry Line Modules', '2026-10-29', '350000.00', 'Delivered') ON DUPLICATE KEY UPDATE `quote_id` = VALUES(`quote_id`), `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`), `created_by_emp_id` = VALUES(`created_by_emp_id`), `created_at` = VALUES(`created_at`), `quote_ref` = VALUES(`quote_ref`), `equipment_scope` = VALUES(`equipment_scope`), `valid_until` = VALUES(`valid_until`), `total_amount` = VALUES(`total_amount`), `status` = VALUES(`status`);
INSERT INTO `quotes` (`quote_id`, `cus_id`, `prod_id`, `quantity`, `unit_price`, `created_by_emp_id`, `created_at`, `quote_ref`, `equipment_scope`, `valid_until`, `total_amount`, `status`) VALUES ('100000', 'CUS-1001', 'PROD-1001', '1', '350000.00', 'EMP-1006', '2026-09-29 20:09:17', 'QUO-9936', 'Telemetry Line Modules', '2026-10-29', '350000.00', 'Delivered') ON DUPLICATE KEY UPDATE `quote_id` = VALUES(`quote_id`), `cus_id` = VALUES(`cus_id`), `prod_id` = VALUES(`prod_id`), `quantity` = VALUES(`quantity`), `unit_price` = VALUES(`unit_price`), `created_by_emp_id` = VALUES(`created_by_emp_id`), `created_at` = VALUES(`created_at`), `quote_ref` = VALUES(`quote_ref`), `equipment_scope` = VALUES(`equipment_scope`), `valid_until` = VALUES(`valid_until`), `total_amount` = VALUES(`total_amount`), `status` = VALUES(`status`);

-- -------------------------------------------------------------------------
-- Table Structure: `documents`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `documents` (
  `doc_id` varchar(15) NOT NULL,
  `file_name` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `classification` enum('Public','Internal','Confidential','TopSecret') NOT NULL,
  `folder` varchar(50) NOT NULL DEFAULT 'projects',
  `department` varchar(10) NOT NULL DEFAULT 'ENG',
  `file_size` varchar(20) NOT NULL DEFAULT '2.0 MB',
  `file_hash` varchar(64) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'Approved',
  `retention_period` varchar(20) NOT NULL DEFAULT '7y',
  `project_ref` varchar(150) DEFAULT NULL,
  `customer_ref` varchar(150) DEFAULT NULL,
  `is_legal_hold` tinyint(1) NOT NULL DEFAULT 0,
  `legal_hold_by_emp_id` varchar(10) DEFAULT NULL,
  `legal_hold_date` datetime DEFAULT NULL,
  `legal_hold_reason` text DEFAULT NULL,
  `owning_system` varchar(50) DEFAULT NULL,
  `owner_emp_id` varchar(10) DEFAULT NULL,
  `related_prj_id` varchar(15) DEFAULT NULL,
  `related_cus_id` varchar(10) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`doc_id`),
  KEY `fk_documents_owner_emp_id` (`owner_emp_id`),
  KEY `fk_documents_related_prj_id` (`related_prj_id`),
  KEY `fk_documents_related_cus_id` (`related_cus_id`),
  CONSTRAINT `fk_documents_owner_emp_id` FOREIGN KEY (`owner_emp_id`) REFERENCES `employees` (`emp_id`),
  CONSTRAINT `fk_documents_related_cus_id` FOREIGN KEY (`related_cus_id`) REFERENCES `customers` (`cus_id`),
  CONSTRAINT `fk_documents_related_prj_id` FOREIGN KEY (`related_prj_id`) REFERENCES `projects` (`prj_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for `documents` (20 rows)
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-001', 'Corporate_Information_Security_Policy.pdf', 'Master enterprise cybersecurity charter & access policy', 'TopSecret', 'governance', 'EXE', '3.8 MB', 'a89f30b9148d423985bf4f481c81c4e97a5b3992b1cf5600ea8b1990c681ea88', 'Approved', 'permanent', 'PRJ-GOV-2026', 'Internal Corporate', '0', NULL, NULL, NULL, 'Admin & Governance', 'EMP-1005', NULL, NULL, '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-002', 'Customer_Onboarding_Standard.pdf', 'Commercial account vetting protocol & KYC', 'Confidential', 'contracts', 'SAL', '1.6 MB', '7b2a9e334f590bb821034f828a1c89283e7428fb17c1817e81037894a8217e92', 'Approved', '7y', 'COMM-STD-2026', 'Commercial Accounts', '0', NULL, NULL, NULL, 'CRM', 'EMP-1006', NULL, NULL, '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-003', 'PRJ-2026-001_Statement_of_Work.pdf', 'Aral Geomatics Group • Optical Sensor Integration SOW', 'Confidential', 'projects', 'ENG', '2.1 MB', '4e1a8b928172c3d4e5f60718293a4b5c6d7e8f90123456789abcdef012345678', 'Approved', '7y', 'PRJ-2026-001 (Aral Geomatics)', 'CUS-1001 (Aral Geomatics Group)', '0', NULL, NULL, NULL, 'File Center', 'EMP-1019', 'PRJ-2026-001', 'CUS-1001', '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-004', 'PRJ-2026-002_Integration_Specification.pdf', 'BaltNord SCADA Ingestion • Reviewed by Farida Iskakova', 'TopSecret', 'projects', 'ENG', '4.5 MB', '9f8e7d6c5b4a3928170192837465abcdeffedcba98765432101234567890fedc', 'In Review', '10y', 'PRJ-2026-002 (BaltNord Process Systems)', 'CUS-1002 (BaltNord Process Systems)', '1', 'EMP-0001', '2026-09-28 22:58:18', 'Preservation order: Litigation and statutory audit freeze', 'File Center', 'EMP-1019', 'PRJ-2026-002', 'CUS-1002', '2026-09-21 19:36:10', '2026-09-28 22:58:18') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-005', 'INV-2026-002_Billing_Record.pdf', 'BaltNord Milestone 1 billing attestation (€120,000)', 'Confidential', 'finance', 'FIN', '890 KB', '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', 'Approved', '7y', 'PRJ-2026-002', 'CUS-1002 (BaltNord Process Systems)', '0', NULL, NULL, NULL, 'Finance', 'EMP-1003', 'PRJ-2026-002', 'CUS-1002', '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-006', 'Employee_Onboarding_Procedure.pdf', 'Standard Operating Procedure • SOP-05 HR Enrollment', 'Confidential', 'hr', 'HR', '1.2 MB', 'abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890', 'Approved', '5y', 'HR-SOP-2026', 'Internal HR', '0', NULL, NULL, NULL, 'HR', 'EMP-1013', NULL, NULL, '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-007', 'Employee_Access_Matrix.xlsx', 'Complete RBAC and clearance register for 95 employees', 'TopSecret', 'governance', 'EXE', '1.9 MB', 'deadbeef1029384756abcdef0192837465bcaefd1234567890fedcba98765432', 'Approved', 'permanent', 'SEC-AUDIT-2026', 'Internal Security Audit', '1', 'EMP-1005', '2026-09-01 09:00:00', 'Statutory access permissions • Annual external audit', 'Admin & Governance', 'EMP-1005', NULL, NULL, '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-008', 'Supplier_Evaluation_2026.pdf', 'Tier-1 industrial transducer vendor scorecard', 'Confidential', 'operations', 'OPS', '2.8 MB', '9876543210fedcba9876543210fedcba9876543210fedcba9876543210fedcba', 'Approved', '5y', 'OPS-SUP-2026', 'Supply Chain Vendors', '0', NULL, NULL, NULL, 'Operations', 'EMP-1011', NULL, NULL, '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-009', 'Optical_Sensor_Product_Catalog.pdf', 'Standard B2B product specifications • Public distribution', 'Public', 'operations', 'SAL', '14.2 MB', '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef', 'Approved', '3y', 'PUB-CAT-2026', 'Public Industrial B2B', '0', NULL, NULL, NULL, 'E-Commerce', 'EMP-1006', NULL, NULL, '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-010', 'API_Integration_Guide.pdf', 'REST & gRPC endpoints protocol for partner systems', 'Internal', 'projects', 'ENG', '3.1 MB', '554433221100aabbccddeeff99887766554433221100aabbccddeeff99887766', 'Approved', '3y', 'DEV-GATEWAY-v4', 'Developer Partners', '0', NULL, NULL, NULL, 'Developer Portal', 'EMP-1017', NULL, NULL, '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-011', 'Disaster_Recovery_Plan.pdf', 'Cold site failover & Almaty datastore replication runbook', 'TopSecret', 'governance', 'EXE', '5.2 MB', 'feefeeddccbbaa99887766554433221100feefeeddccbbaa9988776655443322', 'Approved', 'permanent', 'BCP-DR-2026', 'IT Operations', '0', NULL, NULL, NULL, 'IT Helpdesk', 'EMP-1004', NULL, NULL, '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-012', 'Annual_Corporate_Budget_2026.xlsx', 'Capital allocation • Executive board authorization only', 'TopSecret', 'finance', 'FIN', '4.1 MB', '99887766554433221100feefeeddccbbaa99887766554433221100feefeeddcc', 'Approved', '7y', 'CORP-FIN-2026', 'Corporate Board', '0', NULL, NULL, NULL, 'Finance', 'EMP-1003', NULL, NULL, '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-013', 'Customer_Service_Handbook.pdf', 'Operational guidelines for regional account liaisons', 'Internal', 'hr', 'HR', '2.4 MB', '11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff', 'Approved', '5y', 'INT-TRAIN-2026', 'Internal Support', '0', NULL, NULL, NULL, 'Intranet', 'EMP-1004', NULL, NULL, '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-014', 'PRJ-2026-007_Test_Report.pdf', 'Seismic Vibration Array • Acceptance Testing Certificate', 'Confidential', 'projects', 'ENG', '3.6 MB', '3344556677889900aabbccddeeff11223344556677889900aabbccddeeff1122', 'Approved', '10y', 'PRJ-2026-007 (PetroKaz / Caspian Robotics)', 'CUS-1007 (Caspian Industrial Robotics)', '0', NULL, NULL, NULL, 'File Center', 'EMP-1019', 'PRJ-2026-007', 'CUS-1007', '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-2026-015', 'Board_Risk_Register_2026.xlsx', 'Statutory enterprise risk matrix • Board of Directors', 'TopSecret', 'governance', 'EXE', '2.7 MB', 'bbccddeeff00112233445566778899aabbccddeeff00112233445566778899aa', 'Approved', 'permanent', 'BOARD-RISK-2026', 'Board of Directors', '1', 'EMP-1001', '2026-09-05 11:30:00', 'Board of Directors quarterly risk disclosures', 'Admin & Governance', 'EMP-1005', NULL, NULL, '2026-09-21 19:36:10', '2026-09-27 18:51:35') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-CAL-8812-99', 'Calibration-Cert-VP900.pdf', 'GOST & ISO 17025 Factory Calibration Certificate for VP-900', 'Internal', 'Certificates', 'QA', '1258291', NULL, 'Approved', '7y', 'PRJ-VP-7721', 'CUS-1001', '0', NULL, NULL, NULL, NULL, NULL, 'PRJ-VP-7721', 'CUS-1001', '2026-09-30 02:26:57', '2026-09-30 02:26:57') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-FAT-7721-02', 'FAT-Acceptance-Protocol.pdf', 'Factory Acceptance Test Protocol signed by Severstal QA', 'Confidential', 'Protocols', 'QA', '2149580', NULL, 'Approved', '7y', 'PRJ-VP-7721', 'CUS-1001', '0', NULL, NULL, NULL, NULL, NULL, 'PRJ-VP-7721', 'CUS-1001', '2026-09-30 02:26:57', '2026-09-30 02:26:57') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-SHP-2000', 'Purchase_Order_Severstal_2026.pdf', 'Signed Corporate PO Document (Order #1)', 'Confidential', 'Orders & Procurement', 'SAL', '42', '6906bc39c0b377ba9871eccce043510688663a6b146206ec705d4b3cfea88839', 'Approved', '5 Years', NULL, 'CUS-1001', '0', NULL, NULL, NULL, 'Online Shop B2B (SYS-02)', NULL, NULL, 'CUS-1001', '2026-09-30 02:38:10', '2026-09-30 02:38:10') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-TEST-870', 'Test_Automated_Verification_Policy.pdf', 'Temporary test policy for automated method verification.', 'Confidential', 'policies', 'EXE', '1.2 MB', NULL, 'Approved', '7y', NULL, NULL, '0', NULL, NULL, NULL, 'SYS-11 GOV-CORE', 'EMP-0001', NULL, NULL, '2026-09-28 19:46:08', '2026-09-28 19:46:08') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `documents` (`doc_id`, `file_name`, `description`, `classification`, `folder`, `department`, `file_size`, `file_hash`, `status`, `retention_period`, `project_ref`, `customer_ref`, `is_legal_hold`, `legal_hold_by_emp_id`, `legal_hold_date`, `legal_hold_reason`, `owning_system`, `owner_emp_id`, `related_prj_id`, `related_cus_id`, `created_at`, `updated_at`) VALUES ('DOC-WD-7721-04', 'BF5-Wiring-Diagram-RevC.pdf', 'Complete wiring schematic for Blast Furnace #5 telemetry racks', 'Confidential', 'Technical Schematics', 'Engineerin', '4404019', NULL, 'Approved', '7y', 'PRJ-VP-7721', 'CUS-1001', '0', NULL, NULL, NULL, NULL, NULL, 'PRJ-VP-7721', 'CUS-1001', '2026-09-30 02:26:57', '2026-09-30 02:26:57') ON DUPLICATE KEY UPDATE `doc_id` = VALUES(`doc_id`), `file_name` = VALUES(`file_name`), `description` = VALUES(`description`), `classification` = VALUES(`classification`), `folder` = VALUES(`folder`), `department` = VALUES(`department`), `file_size` = VALUES(`file_size`), `file_hash` = VALUES(`file_hash`), `status` = VALUES(`status`), `retention_period` = VALUES(`retention_period`), `project_ref` = VALUES(`project_ref`), `customer_ref` = VALUES(`customer_ref`), `is_legal_hold` = VALUES(`is_legal_hold`), `legal_hold_by_emp_id` = VALUES(`legal_hold_by_emp_id`), `legal_hold_date` = VALUES(`legal_hold_date`), `legal_hold_reason` = VALUES(`legal_hold_reason`), `owning_system` = VALUES(`owning_system`), `owner_emp_id` = VALUES(`owner_emp_id`), `related_prj_id` = VALUES(`related_prj_id`), `related_cus_id` = VALUES(`related_cus_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);

SET FOREIGN_KEY_CHECKS = 1;
-- =========================================================================
-- End of Online Shop B2B Database Setup Script
-- =========================================================================
